import numpy as np
import pipeline # my bespoke module
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

def numpy_confusion_matrix(actual, predicted):
    # sort and map unique classes to indices
    classes = sorted(list(set(actual) | set(predicted)))
    n = len(classes)
    class_to_idx = {c: i for i, c in enumerate(classes)}
    
    # Init N x N matrix with 0
    matrix = [[0] * n for _ in range(n)]
    
    # Populate matrix
    for a, p in zip(actual, predicted):
        matrix[class_to_idx[a]][class_to_idx[p]] += 1
        
    return np.array(matrix)

def run_evaluation():
    # load data
    DF = pipeline.load_data('processed')

    CUTOFF_DEFAULT = 0.5
    CUTOFF_CALC = 0.67

    predictors = [
        'air_temperature',
        'process_temperature',
        'rotational_speed',
        'torque',
        'tool_wear'
    ]

    X = DF[predictors]
    y = DF['machine_failure']

    # test/train split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # train and fit model
    model = LogisticRegression(class_weight='balanced',max_iter=1000)
    model.fit(X_train, y_train)

    scores = model.predict_proba(X_test)[:, 1]
    model_pred_default = (scores >= CUTOFF_DEFAULT).astype(int)
    model_pred_calculated = (scores >= CUTOFF_CALC).astype(int)

    return model_pred_default, model_pred_calculated, y_test

# if run by itself, print the output (portion generated by Gemini)
if __name__ == '__main__':
    pred_default, pred_calc, y_test = run_evaluation()

    np_cm_default = numpy_confusion_matrix(y_test, pred_default)
    np_cm_calc = numpy_confusion_matrix(y_test, pred_calc)

    print("Numpy Confusion Matrix (Default Threshold 0.5):\n", np_cm_default)
    print("Numpy Confusion Matrix (Calculated Threshold 0.67):\n", np_cm_calc)